package config

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

// ErrNotLoggedIn is returned when no token file exists.
var ErrNotLoggedIn = errors.New("not logged in — run: bbctl login")

// defaultOIDCClientSecret is the Google OAuth Desktop App client secret.
//
// WHY IT IS OK TO HARDCODE THIS:
//   - Desktop App client secrets are public by design (Google's own docs
//     acknowledge they cannot be kept confidential).
//   - PKCE protects the OAuth flow, not this value.
//   - This pattern does NOT apply to other secrets. Do not use it as
//     precedent for API keys, database passwords, or anything else.
//
// When rotating: update the value here, tag a new release.
const defaultOIDCClientSecret = "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"

// Config holds all user-facing configuration.
type Config struct {
	BackendURL         string `yaml:"backend_url"`
	AuthMode           string `yaml:"auth_mode"`           // jwt | sigv4
	OIDCIssuer         string `yaml:"oidc_issuer"`
	OIDCClientID       string `yaml:"oidc_client_id"`
	OIDCAuthEndpoint   string `yaml:"oidc_auth_endpoint"`
	OIDCTokenEndpoint  string `yaml:"oidc_token_endpoint"`
	// OIDCClientSecret is not written to config file. The embedded default is used
	// for all Blackbuck users; BBCTL_OIDC_CLIENT_SECRET overrides for custom OAuth clients.
	OIDCClientSecret   string `yaml:"-"`
	DefaultTimeoutSecs int               `yaml:"default_timeout_secs"`
	DefaultAccountID   string            `yaml:"default_account_id"`
	AccountAliases     map[string]string `yaml:"account_aliases"`
}

// DefaultConfigDir returns ~/.bbctl.
func DefaultConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".bbctl"), nil
}

// LoadOrDefault loads config.yaml from configDir, or returns sensible defaults if absent.
func LoadOrDefault(configDir string) (*Config, error) {
	cfg := &Config{
		AuthMode:           "jwt",
		DefaultTimeoutSecs: 30,
		BackendURL:         "https://bbctl.blackbuck.com",
		OIDCIssuer:         "https://accounts.google.com",
		OIDCClientID:       "396628175360-g90ptoadcl2coqrtk09oa2625a0k4ppf.apps.googleusercontent.com",
		OIDCAuthEndpoint:   "https://accounts.google.com/o/oauth2/v2/auth",
		OIDCTokenEndpoint:  "https://oauth2.googleapis.com/token",
		DefaultAccountID:   "",
		OIDCClientSecret:   defaultOIDCClientSecret,
	}
	data, err := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	if err == nil {
		if err := yaml.Unmarshal(data, cfg); err != nil {
			return nil, err
		}
	}
	if cfg.DefaultTimeoutSecs == 0 {
		cfg.DefaultTimeoutSecs = 30
	}
	// BBCTL_BACKEND_URL env var takes highest precedence.
	if v := os.Getenv("BBCTL_BACKEND_URL"); v != "" {
		cfg.BackendURL = v
	}
	// BBCTL_OIDC_CLIENT_SECRET overrides the embedded default — only needed when
	// pointing at a custom OAuth client.
	if v := os.Getenv("BBCTL_OIDC_CLIENT_SECRET"); v != "" {
		cfg.OIDCClientSecret = v
	}
	return cfg, nil
}

// ResolveAccount maps an alias or raw account ID to a 12-digit account ID.
// Returns the input unchanged if it is already a 12-digit ID or unknown.
// Returns "" for empty input.
func (c *Config) ResolveAccount(input string) string {
	if input == "" {
		return ""
	}
	if matched, _ := regexp.MatchString(`^\d{12}$`, input); matched {
		return input
	}
	lower := strings.ToLower(input)
	for alias, id := range c.AccountAliases {
		if strings.ToLower(alias) == lower {
			return id
		}
	}
	return input
}

// WriteDefaultConfig creates config.yaml with commented examples if it doesn't exist.
func WriteDefaultConfig(configDir string) error {
	path := filepath.Join(configDir, "config.yaml")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return os.WriteFile(path, []byte(defaultConfigTemplate), 0600)
}

const defaultConfigTemplate = `# bbctl configuration — generated by bbctl login

# Default AWS account ID used when --account is omitted.
# default_account_id: "735317561518"

# AWS account aliases — use names instead of 12-digit IDs with -a / --account.
account_aliases:
  zinka:   "735317561518"
  divum:   "597070799581"
  finserv: "075903075452"
  tzf:     "476114138058"
`
